services:
  web:
    image: vzagoruyko/self-checkout-backend:latest
    env_file:
      - .env.prod
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:16
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    restart: always

  celery:
    image: vzagoruyko/self-checkout-backend:latest
    command: celery -A core worker --loglevel=info
    env_file:
      - .env.prod
    depends_on:
      - redis
      - db
    restart: always

  celery-beat:
    image: vzagoruyko/self-checkout-backend:latest
    command: celery -A core beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env.prod
    depends_on:
      - redis
      - db
    restart: always

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/usr/share/nginx/html/static:ro
      - /srv/self-checkout-backend/letsencrypt:/etc/letsencrypt:ro
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  static_volume:
