version: "3.9"

services:
  web:
    build: .
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - POSTGRES_DB=self_checkout
      - POSTGRES_USER=self_checkout_user
      - POSTGRES_PASSWORD=self_checkout_pass
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: self_checkout
      POSTGRES_USER: self_checkout_user
      POSTGRES_PASSWORD: self_checkout_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
