# Generated by Django 5.2.6 on 2025-09-18 09:39

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="historicalcategory",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Категория",
                "verbose_name_plural": "historical Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalorder",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Заказ",
                "verbose_name_plural": "historical Заказы",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpayment",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Оплата",
                "verbose_name_plural": "historical Оплаты",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpointofsale",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Точка продаж",
                "verbose_name_plural": "historical Точки продаж",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalproduct",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Товар/Блюдо",
                "verbose_name_plural": "historical Товары/Блюда",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Заказ", "verbose_name_plural": "Заказы"},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Позиция заказа",
                "verbose_name_plural": "Позиции заказа",
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Оплата", "verbose_name_plural": "Оплаты"},
        ),
        migrations.AlterModelOptions(
            name="pointofsale",
            options={
                "verbose_name": "Точка продаж",
                "verbose_name_plural": "Точки продаж",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "verbose_name": "Товар/Блюдо",
                "verbose_name_plural": "Товары/Блюда",
            },
        ),
        migrations.AlterModelOptions(
            name="receipt",
            options={
                "verbose_name": "Фискальный чек",
                "verbose_name_plural": "Фискальные чеки",
            },
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="barcode",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="Штрихкод",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Штрихкод",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название категории"),
        ),
        migrations.AlterField(
            model_name="historicalcategory",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название категории"),
        ),
        migrations.AlterField(
            model_name="historicalorder",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="historicalorder",
            name="pos",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pos.pointofsale",
                verbose_name="Точка продаж",
            ),
        ),
        migrations.AlterField(
            model_name="historicalorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("paid", "Оплачен"),
                    ("cancelled", "Отменён"),
                ],
                default="new",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="historicalorder",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Итоговая сумма",
            ),
        ),
        migrations.AlterField(
            model_name="historicalorder",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Обновлено"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpayment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Сумма"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpayment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pos.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpayment",
            name="payment_type",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("card", "Карта")],
                max_length=20,
                verbose_name="Тип оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpayment",
            name="processed_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Дата обработки"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В ожидании"),
                    ("paid", "Оплачен"),
                    ("failed", "Неудача"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpointofsale",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpointofsale",
            name="location",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Местоположение"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpointofsale",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="historicalpointofsale",
            name="status",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AlterField(
            model_name="historicalpointofsale",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Обновлено"
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="available",
            field=models.BooleanField(default=True, verbose_name="В наличии"),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="category",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pos.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="order",
            name="pos",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="pos.pointofsale",
                verbose_name="Точка продаж",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("paid", "Оплачен"),
                    ("cancelled", "Отменён"),
                ],
                default="new",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Итоговая сумма",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="pos.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена на момент покупки"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="pos.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Сумма"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="pos.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("card", "Карта")],
                max_length=20,
                verbose_name="Тип оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="processed_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата обработки"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В ожидании"),
                    ("paid", "Оплачен"),
                    ("failed", "Неудача"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="pointofsale",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="pointofsale",
            name="location",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Местоположение"
            ),
        ),
        migrations.AlterField(
            model_name="pointofsale",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="pointofsale",
            name="status",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AlterField(
            model_name="pointofsale",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="product",
            name="available",
            field=models.BooleanField(default=True, verbose_name="В наличии"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="pos.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="fiscal_data",
            field=models.JSONField(verbose_name="Фискальные данные"),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="issued_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата выдачи"),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipt",
                to="pos.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="receipt_number",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Номер чека"
            ),
        ),
        migrations.CreateModel(
            name="HistoricalStock",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Количество"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pos",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pos.pointofsale",
                        verbose_name="Точка продаж",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pos.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Остаток товара",
                "verbose_name_plural": "historical Остатки товаров",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Количество"),
                ),
                (
                    "pos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="pos.pointofsale",
                        verbose_name="Точка продаж",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="pos.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Остаток товара",
                "verbose_name_plural": "Остатки товаров",
                "unique_together": {("pos", "product")},
            },
        ),
    ]
