# Generated by Django 5.2.6 on 2025-09-21 07:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstock",
            name="quantity",
            field=models.IntegerField(default=0, verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="pointofsaletoken",
            name="token",
            field=models.CharField(
                default=uuid.UUID("786d9f4b-e3bc-4487-a104-d12bad48145b"),
                max_length=40,
                unique=True,
                verbose_name="Токен",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="quantity",
            field=models.IntegerField(default=0, verbose_name="Количество"),
        ),
    ]
