# Generated by Django 5.2.6 on 2025-09-21 15:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0002_alter_historicalstock_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pointofsaletoken",
            name="token",
            field=models.CharField(
                default=uuid.UUID("cba1dec1-5d27-4ac5-ba5b-94ae608e5f5a"),
                max_length=40,
                unique=True,
                verbose_name="Токен",
            ),
        ),
    ]
