# Generated by Django 5.2.6 on 2025-09-18 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0002_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.AlterModelOptions(
            name="historicalcategory",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical category",
                "verbose_name_plural": "historical categorys",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalorder",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical order",
                "verbose_name_plural": "historical orders",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpayment",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical payment",
                "verbose_name_plural": "historical payments",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpointofsale",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical point of sale",
                "verbose_name_plural": "historical point of sales",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalproduct",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical product",
                "verbose_name_plural": "historical products",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalstock",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical stock",
                "verbose_name_plural": "historical stocks",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={},
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={},
        ),
        migrations.AlterModelOptions(
            name="pointofsale",
            options={},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.AlterModelOptions(
            name="receipt",
            options={},
        ),
        migrations.AlterModelOptions(
            name="stock",
            options={},
        ),
        migrations.RemoveField(
            model_name="historicalorder",
            name="status",
        ),
        migrations.RemoveField(
            model_name="historicalpayment",
            name="status",
        ),
        migrations.RemoveField(
            model_name="historicalproduct",
            name="available",
        ),
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="status",
        ),
        migrations.RemoveField(
            model_name="product",
            name="available",
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="state",
            field=models.CharField(
                choices=[
                    ("CREATED", "Создан"),
                    ("PAID", "Оплачен"),
                    ("CANCELLED", "Отменён"),
                ],
                default="CREATED",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="historicalpayment",
            name="state",
            field=models.CharField(
                choices=[
                    ("PENDING", "В ожидании"),
                    ("PAID", "Оплачен"),
                    ("FAILED", "Неудача"),
                ],
                default="PENDING",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="historicalpointofsale",
            name="code",
            field=models.CharField(
                default="test", max_length=50, verbose_name="Код точки"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="weight",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Вес/кол-во"
            ),
        ),
        migrations.AddField(
            model_name="historicalstock",
            name="available_for_sale",
            field=models.BooleanField(default=True, verbose_name="Доступно к продаже"),
        ),
        migrations.AddField(
            model_name="order",
            name="state",
            field=models.CharField(
                choices=[
                    ("CREATED", "Создан"),
                    ("PAID", "Оплачен"),
                    ("CANCELLED", "Отменён"),
                ],
                default="CREATED",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Общая цена"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="state",
            field=models.CharField(
                choices=[
                    ("PENDING", "В ожидании"),
                    ("PAID", "Оплачен"),
                    ("FAILED", "Неудача"),
                ],
                default="PENDING",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="pointofsale",
            name="code",
            field=models.CharField(
                default="test", max_length=50, verbose_name="Код точки"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Вес/кол-во"
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="link",
            field=models.URLField(blank=True, verbose_name="Ссылка на чек"),
        ),
        migrations.AddField(
            model_name="stock",
            name="available_for_sale",
            field=models.BooleanField(default=True, verbose_name="Доступно к продаже"),
        ),
        migrations.AlterField(
            model_name="historicalpayment",
            name="payment_type",
            field=models.CharField(
                choices=[("card", "Карта"), ("sbp", "СБП")],
                max_length=20,
                verbose_name="Метод оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[("card", "Карта"), ("sbp", "СБП")],
                max_length=20,
                verbose_name="Метод оплаты",
            ),
        ),
        migrations.CreateModel(
            name="OrderComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="pos.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
        ),
    ]
