# Generated by Django 5.2.6 on 2025-09-18 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0003_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="historicalcategory",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Категория",
                "verbose_name_plural": "historical Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalorder",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Заказ",
                "verbose_name_plural": "historical Заказы",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpayment",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Оплата",
                "verbose_name_plural": "historical Оплаты",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpointofsale",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Точка продаж",
                "verbose_name_plural": "historical Точки продаж",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalproduct",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Товар",
                "verbose_name_plural": "historical Товары",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalstock",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Остаток",
                "verbose_name_plural": "historical Остатки",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Заказ", "verbose_name_plural": "Заказы"},
        ),
        migrations.AlterModelOptions(
            name="ordercomment",
            options={
                "verbose_name": "Комментарий к заказу",
                "verbose_name_plural": "Комментарии к заказам",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Позиция заказа",
                "verbose_name_plural": "Позиции заказа",
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Оплата", "verbose_name_plural": "Оплаты"},
        ),
        migrations.AlterModelOptions(
            name="pointofsale",
            options={
                "verbose_name": "Точка продаж",
                "verbose_name_plural": "Точки продаж",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AlterModelOptions(
            name="receipt",
            options={
                "verbose_name": "Фискальный чек",
                "verbose_name_plural": "Фискальные чеки",
            },
        ),
        migrations.AlterModelOptions(
            name="stock",
            options={"verbose_name": "Остаток", "verbose_name_plural": "Остатки"},
        ),
        migrations.RemoveField(
            model_name="historicalpayment",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="order",
        ),
        migrations.AddField(
            model_name="receipt",
            name="payment",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipt",
                to="pos.payment",
                verbose_name="Платёж",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalorder",
            name="state",
            field=models.CharField(
                choices=[
                    ("CREATED", "Создан"),
                    ("PAID", "Оплачен"),
                    ("CANCELLED", "Отменён"),
                ],
                default="CREATED",
                max_length=150,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpayment",
            name="state",
            field=models.CharField(
                choices=[
                    ("PENDING", "В ожидании"),
                    ("PAID", "Оплачен"),
                    ("FAILED", "Неудача"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpointofsale",
            name="code",
            field=models.CharField(
                db_index=True, max_length=50, verbose_name="Код точки"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(
                choices=[
                    ("CREATED", "Создан"),
                    ("PAID", "Оплачен"),
                    ("CANCELLED", "Отменён"),
                ],
                default="CREATED",
                max_length=150,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="state",
            field=models.CharField(
                choices=[
                    ("PENDING", "В ожидании"),
                    ("PAID", "Оплачен"),
                    ("FAILED", "Неудача"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="pointofsale",
            name="code",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Код точки"
            ),
        ),
    ]
