# Generated by Django 5.2.6 on 2025-09-22 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0003_alter_pointofsaletoken_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pointofsaletoken",
            name="token",
            field=models.CharField(
                default=uuid.UUID("55cebc40-0fc9-4cde-9e36-bc091e003015"),
                max_length=40,
                unique=True,
                verbose_name="Токен",
            ),
        ),
    ]
