# Generated by Django 5.2.6 on 2025-09-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0004_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpayment",
            name="payment_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Ссылка на оплату (эквайринг)"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Ссылка на оплату (эквайринг)"
            ),
        ),
    ]
