# Generated by Django 5.2.6 on 2025-10-05 15:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0004_alter_pointofsaletoken_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pointofsaletoken",
            name="token",
            field=models.CharField(
                default=uuid.UUID("f3badede-8b64-4923-b7b0-f7447040a17f"),
                max_length=40,
                unique=True,
                verbose_name="Токен",
            ),
        ),
    ]
