# Generated by Django 5.2.6 on 2025-09-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0005_historicalpayment_payment_url_payment_payment_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorder",
            name="state",
            field=models.CharField(
                choices=[
                    ("CREATED", "Создан"),
                    ("PAID", "Оплачен"),
                    ("CANCELLED", "Отменён"),
                    ("ARCHIEVE", "Архивирован"),
                ],
                default="CREATED",
                max_length=150,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(
                choices=[
                    ("CREATED", "Создан"),
                    ("PAID", "Оплачен"),
                    ("CANCELLED", "Отменён"),
                    ("ARCHIEVE", "Архивирован"),
                ],
                default="CREATED",
                max_length=150,
                verbose_name="Статус",
            ),
        ),
    ]
