# Generated by Django 5.2.6 on 2025-09-19 10:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0006_alter_historicalorder_state_alter_order_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="PointOfSaleToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(default=uuid.uuid4, max_length=40, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pos",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_token",
                        to="pos.pointofsale",
                    ),
                ),
            ],
        ),
    ]
