name: Self Checkout Backend CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: docker compose -f docker-compose.ci.yml build

      - name: Start services
        run: docker compose -f docker-compose.ci.yml up -d

      - name: Install dependencies in container
        run: docker compose run --rm web poetry install --no-root --no-interaction --no-ansi

      - name: Run migrations
        run: docker compose run --rm web python manage.py migrate --noinput

      - name: Run tests
        run: docker compose run --rm web pytest --tb=short -o log_cli=true --cov=.

      - name: Tear down
        run: docker compose -f docker-compose.ci.yml down -v
